version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: server
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - ./server/.env