name: Deploying To Production
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and rolling out deployment
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd server
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "SOCKET_URI=${{ secrets.SOCKET_URI }}" >> .env
            echo "RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}" >> .env
            cd razor_webhook_tinker
            git fetch origin main
            git reset --hard origin/main
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml up --build -d 
            exit
            